name: trackwise
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  http: ^1.2.2
  mobile_scanner: ^6.0.1
  qr_scanner_overlay: ^0.0.2
  qr_flutter: ^4.1.0

  # qr_code_scanner: ^0.4.0

  drift: ^2.21.0
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.0.11
  path: ^1.8.3 
  
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.2
  sqlite3: ^2.4.7
  shared_preferences: ^2.3.2
  flutter_email_sender: ^6.0.3
  excel: ^4.0.6
  file_picker: ^8.1.7
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_animate: ^4.5.2
  permission_handler: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.13
  mockito: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

    - family: Merienda
      fonts:
        - asset: assets/fonts/Merienda-SemiBold.ttf


  
